timeout: 10m
exit-code: 1
format: table
severity:
  - CRITICAL
  - HIGH
  - MEDIUM
vulnerability:
  type:
    - os
    - library
scan:
  skip-dirs:
    - node_modules
    - .git
  security-checks:
    - vuln
    - config
    - secret
cache:
  dir: .trivycache
  clear: false
