name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and Test
      run: |
        # Run tests
        docker-compose -f docker/docker-compose.yml run --rm test
        
        # Build and push Docker image
        docker build -t ${{ secrets.REGISTRY_URL }}/app:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_URL }}/app:${{ github.sha }}
        
        # Tag as latest if on main branch
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker tag ${{ secrets.REGISTRY_URL }}/app:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/app:latest
          docker push ${{ secrets.REGISTRY_URL }}/app:latest
        fi
